# Generated by Django 4.1.3 on 2022-11-19 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PuchaseOrder',
            new_name='PurchaseOrder',
        ),
    ]
