# Generated by Django 4.1.3 on 2022-11-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_puchaseorder_purchaseorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
