# Generated by Django 4.1.3 on 2022-11-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_stock_stock_id_alter_stock_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
