# Generated by Django 4.1.3 on 2022-11-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_purchaseorder_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='valuation',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
    ]
